// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_id_ from "./routes/[id].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $EnvContext from "./islands/EnvContext.tsx";
import * as $OpenButton from "./islands/OpenButton.tsx";
import * as $PaginationButton from "./islands/PaginationButton.tsx";
import * as $ShareButton from "./islands/ShareButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[id].tsx": $_id_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/EnvContext.tsx": $EnvContext,
    "./islands/OpenButton.tsx": $OpenButton,
    "./islands/PaginationButton.tsx": $PaginationButton,
    "./islands/ShareButton.tsx": $ShareButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
